# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_log_det_disp_cpp <- function(H, nD3, q, p) {
    .Call(`_hhjm_get_log_det_disp_cpp`, H, nD3, q, p)
}

get_invH_disp_cpp <- function(H, nD3, q, p) {
    .Call(`_hhjm_get_invH_disp_cpp`, H, nD3, q, p)
}

get_trace_disp_cpp <- function(myDmat, invH, uniqueID, p_par, p, q, subject_id) {
    .Call(`_hhjm_get_trace_disp_cpp`, myDmat, invH, uniqueID, p_par, p, q, subject_id)
}

